<?php
require_once __DIR__ . '/db.php';
require_once __DIR__ . '/includes/layout.php';
require_auth();

$pdo = getDB();

// Determine device status
$location = $pdo->query('SELECT location FROM candidates LIMIT 1')->fetchColumn() ?: 'Not Configured';
$candidates_count = $pdo->query('SELECT COUNT(*) FROM candidates')->fetchColumn();
$positions_count = $pdo->query('SELECT COUNT(*) FROM positions')->fetchColumn();
$total_votes = $pdo->query('SELECT COALESCE(SUM(total_votes), 0) FROM results')->fetchColumn();

layout_header('Dashboard', 'dashboard');
$success = flash_get('success');
$error = flash_get('error');
$print_init = flash_get('print_init');
?>

<?php if ($print_init): ?>
<script>
    window.open('<?= ROOT_URL ?>/election_return.php?type=init', '_blank');
</script>
<?php endif; ?>

<?php if ($success): ?>
<div class="mb-4 p-3 bg-green-50 border border-green-200 text-green-700 text-xs rounded"><?= e($success) ?></div>
<?php endif; ?>
<?php if ($error): ?>
<div class="mb-4 p-3 bg-red-50 border border-red-200 text-red-600 text-xs rounded"><?= e($error) ?></div>
<?php endif; ?>

<div class="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
    <!-- Device Status -->
    <div class="bg-white border border-gray-200 rounded-xl p-6 shadow-sm text-sm text-gray-600">
        <p class="font-bold text-gray-800 mb-2">Operational Guide:</p>
        <ol class="list-decimal list-inside space-y-1.5 ml-1 text-gray-600">
            <li>Import the configuration JSON file generated by the Main Server.</li>
            <li>Open the Ballot form to allow voters to cast their votes.</li>
            <li>Once voting is complete, Export the encrypted results JSON.</li>
            <li>Load the exported file back into the Main Server.</li>
        </ol>
    </div>

    <!-- Stats Card -->
    <div class="bg-white border border-gray-200 rounded-xl p-6 shadow-sm">
        <h3 class="text-sm font-semibold text-gray-500 uppercase tracking-wider mb-4 border-b border-gray-100 pb-2">Device Status</h3>
        <div class="space-y-4">
            <div class="flex justify-between items-center">
                <span class="text-gray-600">Assigned Location</span>
                <span class="font-medium px-3 py-1 bg-navy-50 text-navy rounded-full text-xs">
                    <?= e($location) ?>
                </span>
            </div>
            <div class="flex justify-between items-center">
                <span class="text-gray-600">Configuration</span>
                <?php if ($candidates_count > 0): ?>
                    <span class="text-green-600 font-medium flex items-center gap-1">
                        <span class="w-2 h-2 rounded-full bg-green-500"></span> Ready
                    </span>
                <?php else: ?>
                    <span class="text-amber-600 font-medium flex items-center gap-1">
                        <span class="w-2 h-2 rounded-full bg-amber-500"></span> Pending Import
                    </span>
                <?php endif; ?>
            </div>
            <div class="flex justify-between items-center pt-2 border-t border-gray-50">
                <span class="text-gray-600">Loaded Positions</span>
                <span class="font-medium text-gray-800"><?= $positions_count ?></span>
            </div>
            <div class="flex justify-between items-center">
                <span class="text-gray-600">Loaded Candidates</span>
                <span class="font-medium text-gray-800"><?= $candidates_count ?></span>
            </div>
            
            <div class="pt-4 mt-4 border-t border-gray-100">
                <div class="mb-3 p-3 bg-amber-50 border border-amber-200 text-amber-700 text-xs rounded">
                    <strong>Warning:</strong> Importing a new configuration or resetting will erase all current local votes.
                </div>
                <div class="flex gap-2">
                    <form method="POST" action="<?= ROOT_URL ?>/process_import.php" enctype="multipart/form-data" class="flex-1">
                        <label class="block w-full bg-navy hover:bg-navy-700 text-white text-center font-medium py-2 rounded transition-colors cursor-pointer text-sm">
                            Import Config
                            <input type="file" name="import_file" accept=".json" class="hidden" onchange="this.form.submit()">
                        </label>
                    </form>
                    <form method="POST" action="<?= ROOT_URL ?>/reset.php" onsubmit="return confirm('Are you absolutely sure? This will erase all candidates and locally stored votes. This action cannot be undone.');">
                        <input type="hidden" name="reset_device" value="1">
                        <button type="submit" class="bg-white border border-red-200 text-red-600 hover:bg-red-50 font-medium py-2 px-4 rounded transition-colors shadow-sm text-sm" <?= !$location || $location === 'Not Configured' ? 'disabled' : '' ?>>
                            Reset
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>



<?php layout_footer(); ?>
